package com.gameexpert.world.dimension.voidend;

import com.gameexpert.terrain.Blocks;
import java.util.Base64;
import java.util.List;

/**
 * [END-CITY] 핀 26.3-snapshot-7 client jar(SHA-1 16169fc68cc553b82f495bb2896bde6170aa51a7)의 data/minecraft/structure/end_city/*.nbt 에서 client/scripts/gen-end-city-templates.py 가 생성한 파일이다. 손으로 고치지 말 것.
 * 정적판 {@code client/src/world/dimensions/voidEnd/endCityTemplates.ts} 와 같은 표다.
 *
 * <p>격자 인덱스 = (y · sizeZ + z) · sizeX + x, 값 = {@link #VANILLA_STATES} 순번({@link #EMPTY} 는 템플릿에
 * 없는 칸 — 바닐라는 아무것도 놓지 않는다). {@link #STATE_MAP} 은
 * [state][Rotation 서수] → (블록 ID &lt;&lt; 8 | state 바이트)이다.
 */
public final class EndCityTemplates {
    private EndCityTemplates() {
    }

    /** 템플릿 블록 목록에 없는 칸. */
    public static final int EMPTY = 255;

    /** 원본 템플릿 sha256(무결성 대조용, 이름순). */
    public static final List<String> SOURCE_SHA256 = List.of(
            "base_floor 5085957f6136c2a76a8105a8d78aa38a9eee8f91d35da84523ac8b06c17432a7",
            "base_roof 969fa40980002d3958c695ace089f473040992dad9579a8bfbbef6c402d57553",
            "bridge_end 510126692b3283e1c94ee50152e409923d5cc78fc56c826aa6c0b1efef67f63a",
            "bridge_gentle_stairs fa0094433a04306d793540f066d81f6c5b1103c6eb327b036da97ad6f42bdf64",
            "bridge_piece b388ee9aada05c7325abef1e75fb0187e9bb46c2fce61549578712b9f6bf183f",
            "bridge_steep_stairs 915b8b20f014285cda26a31373dfc59a50aec978f732a3cf3f29f717b806205f",
            "fat_tower_base 4305e5e1fbdaa2c5fa647f62af57817be6387c60eb666a8bf50ea85cf7096e65",
            "fat_tower_middle a21c0fbae713fb70a80aae9ae2d676e9ef8bf0258ca7d5b3b527b11132596e29",
            "fat_tower_top d92ac84991cfdc70f5423eb3b8618f5922e191fcaa2c8a92f4c08b95f85e577a",
            "second_floor_1 79b50b3a9358131ee66ec325075921c67ad117250c526c6af7176c03529b2407",
            "second_floor_2 231ed4134630e8ce462d26e88ff944ff6ed83281dff132714d902e3c77f0a1dd",
            "second_roof bb78347e39a8d0dbba12529979e6a37091fafbf7b6dfcdecd13f1267a50b7cd8",
            "ship 6901faa3e95e8f2acc7e37ce0731a54914365e1657dc8e29f3f42ce6c0a92a8b",
            "third_floor_1 864f7765c17dbb282d0769bf8a81ffe289c6dbdbd07df28a9a2596668bbe83e2",
            "third_floor_2 22b0e01c3bd1c5246a5dfbf004c88244560af72a512a316d29d8e3af5b0da16f",
            "third_roof 135ca98395bac7fab967ab5658d169e3183c2c310b57ec6a922111a39be19f5b",
            "tower_base d38c41b89605784d462ab620f578efe676fae62da1c55ff0a96848514a2720e0",
            "tower_floor ba867a5a18809a5af5b613b41c8958f68c8463bef7a99a61d4ef13ee2832da5d",
            "tower_piece 0536d2cb89b73db1694ba19b2152e82592e1de98b950777fd522779fdf2aa193",
            "tower_top a2f858a900cd60564f504c8c28c3a0ddc5bcaedf26fea6a47a6ab6afadf65f95");

    public static final List<String> VANILLA_STATES = List.of(
            "minecraft:purpur_block",
            "minecraft:purpur_pillar[axis=y]",
            "minecraft:end_stone_bricks",
            "minecraft:magenta_stained_glass",
            "minecraft:air",
            "minecraft:purpur_stairs[facing=north,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:structure_block[mode=data]",
            "minecraft:purpur_stairs[facing=east,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:purpur_stairs[facing=east,half=top,shape=straight,waterlogged=false]",
            "minecraft:purpur_stairs[facing=east,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:purpur_stairs[facing=north,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:purpur_stairs[facing=south,half=top,shape=straight,waterlogged=false]",
            "minecraft:purpur_stairs[facing=north,half=top,shape=straight,waterlogged=false]",
            "minecraft:purpur_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:purpur_stairs[facing=south,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:purpur_stairs[facing=west,half=top,shape=straight,waterlogged=false]",
            "minecraft:purpur_stairs[facing=west,half=bottom,shape=straight,waterlogged=false]",
            "minecraft:purpur_stairs[facing=west,half=top,shape=outer_right,waterlogged=false]",
            "minecraft:end_rod[facing=up]",
            "minecraft:purpur_pillar[axis=z]",
            "minecraft:purpur_slab[type=top,waterlogged=false]",
            "minecraft:purpur_slab[type=bottom,waterlogged=false]",
            "minecraft:purpur_pillar[axis=x]",
            "minecraft:end_rod[facing=east]",
            "minecraft:end_rod[facing=west]",
            "minecraft:end_rod[facing=south]",
            "minecraft:end_rod[facing=north]",
            "minecraft:purpur_stairs[facing=east,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:purpur_stairs[facing=east,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:chest[facing=east,type=single,waterlogged=false]",
            "minecraft:chest[facing=north,type=single,waterlogged=false]",
            "minecraft:obsidian",
            "minecraft:purpur_stairs[facing=south,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:purpur_stairs[facing=east,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:purpur_stairs[facing=north,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:purpur_stairs[facing=south,half=bottom,shape=inner_left,waterlogged=false]",
            "minecraft:ladder[facing=south,waterlogged=false]",
            "minecraft:purpur_stairs[facing=south,half=bottom,shape=inner_right,waterlogged=false]",
            "minecraft:purpur_stairs[facing=west,half=bottom,shape=inner_left,waterlogged=false]",
            "minecraft:purpur_stairs[facing=east,half=bottom,shape=inner_right,waterlogged=false]",
            "minecraft:purpur_stairs[facing=west,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:purpur_stairs[facing=west,half=top,shape=outer_left,waterlogged=false]",
            "minecraft:chest[facing=south,type=single,waterlogged=false]",
            "minecraft:brewing_stand[has_bottle_0=true,has_bottle_1=false,has_bottle_2=true]",
            "minecraft:dragon_wall_head[facing=north,powered=false]",
            "minecraft:purpur_stairs[facing=north,half=bottom,shape=outer_right,waterlogged=false]",
            "minecraft:purpur_stairs[facing=north,half=bottom,shape=outer_left,waterlogged=false]",
            "minecraft:ender_chest[facing=south,waterlogged=false]",
            "minecraft:ladder[facing=north,waterlogged=false]",
            "minecraft:purpur_stairs[facing=east,half=top,shape=inner_right,waterlogged=false]",
            "minecraft:purpur_stairs[facing=north,half=top,shape=inner_right,waterlogged=false]",
            "minecraft:purpur_stairs[facing=south,half=top,shape=inner_right,waterlogged=false]",
            "minecraft:purpur_stairs[facing=west,half=top,shape=inner_right,waterlogged=false]",
            "minecraft:magenta_wall_banner[facing=west]",
            "minecraft:magenta_wall_banner[facing=north]",
            "minecraft:magenta_wall_banner[facing=south]",
            "minecraft:magenta_wall_banner[facing=east]");

    public static final int[][] STATE_MAP = {
        {Blocks.PURPUR_BLOCK << 8 | 0, Blocks.PURPUR_BLOCK << 8 | 0, Blocks.PURPUR_BLOCK << 8 | 0, Blocks.PURPUR_BLOCK << 8 | 0},
        {Blocks.PURPUR_PILLAR << 8 | 0, Blocks.PURPUR_PILLAR << 8 | 0, Blocks.PURPUR_PILLAR << 8 | 0, Blocks.PURPUR_PILLAR << 8 | 0},
        {Blocks.END_STONE_BRICKS << 8 | 0, Blocks.END_STONE_BRICKS << 8 | 0, Blocks.END_STONE_BRICKS << 8 | 0, Blocks.END_STONE_BRICKS << 8 | 0},
        {Blocks.MAGENTA_STAINED_GLASS << 8 | 0, Blocks.MAGENTA_STAINED_GLASS << 8 | 0, Blocks.MAGENTA_STAINED_GLASS << 8 | 0, Blocks.MAGENTA_STAINED_GLASS << 8 | 0},
        {Blocks.AIR << 8 | 0, Blocks.AIR << 8 | 0, Blocks.AIR << 8 | 0, Blocks.AIR << 8 | 0},
        {Blocks.PURPUR_STAIRS << 8 | 0, Blocks.PURPUR_STAIRS << 8 | 1, Blocks.PURPUR_STAIRS << 8 | 2, Blocks.PURPUR_STAIRS << 8 | 3},
        {Blocks.AIR << 8 | 0, Blocks.AIR << 8 | 0, Blocks.AIR << 8 | 0, Blocks.AIR << 8 | 0},
        {Blocks.PURPUR_STAIRS << 8 | 37, Blocks.PURPUR_STAIRS << 8 | 38, Blocks.PURPUR_STAIRS << 8 | 39, Blocks.PURPUR_STAIRS << 8 | 36},
        {Blocks.PURPUR_STAIRS << 8 | 5, Blocks.PURPUR_STAIRS << 8 | 6, Blocks.PURPUR_STAIRS << 8 | 7, Blocks.PURPUR_STAIRS << 8 | 4},
        {Blocks.PURPUR_STAIRS << 8 | 1, Blocks.PURPUR_STAIRS << 8 | 2, Blocks.PURPUR_STAIRS << 8 | 3, Blocks.PURPUR_STAIRS << 8 | 0},
        {Blocks.PURPUR_STAIRS << 8 | 36, Blocks.PURPUR_STAIRS << 8 | 37, Blocks.PURPUR_STAIRS << 8 | 38, Blocks.PURPUR_STAIRS << 8 | 39},
        {Blocks.PURPUR_STAIRS << 8 | 6, Blocks.PURPUR_STAIRS << 8 | 7, Blocks.PURPUR_STAIRS << 8 | 4, Blocks.PURPUR_STAIRS << 8 | 5},
        {Blocks.PURPUR_STAIRS << 8 | 4, Blocks.PURPUR_STAIRS << 8 | 5, Blocks.PURPUR_STAIRS << 8 | 6, Blocks.PURPUR_STAIRS << 8 | 7},
        {Blocks.PURPUR_STAIRS << 8 | 2, Blocks.PURPUR_STAIRS << 8 | 3, Blocks.PURPUR_STAIRS << 8 | 0, Blocks.PURPUR_STAIRS << 8 | 1},
        {Blocks.PURPUR_STAIRS << 8 | 38, Blocks.PURPUR_STAIRS << 8 | 39, Blocks.PURPUR_STAIRS << 8 | 36, Blocks.PURPUR_STAIRS << 8 | 37},
        {Blocks.PURPUR_STAIRS << 8 | 7, Blocks.PURPUR_STAIRS << 8 | 4, Blocks.PURPUR_STAIRS << 8 | 5, Blocks.PURPUR_STAIRS << 8 | 6},
        {Blocks.PURPUR_STAIRS << 8 | 3, Blocks.PURPUR_STAIRS << 8 | 0, Blocks.PURPUR_STAIRS << 8 | 1, Blocks.PURPUR_STAIRS << 8 | 2},
        {Blocks.PURPUR_STAIRS << 8 | 39, Blocks.PURPUR_STAIRS << 8 | 36, Blocks.PURPUR_STAIRS << 8 | 37, Blocks.PURPUR_STAIRS << 8 | 38},
        {Blocks.END_ROD << 8 | 0, Blocks.END_ROD << 8 | 0, Blocks.END_ROD << 8 | 0, Blocks.END_ROD << 8 | 0},
        {Blocks.PURPUR_PILLAR << 8 | 2, Blocks.PURPUR_PILLAR << 8 | 1, Blocks.PURPUR_PILLAR << 8 | 2, Blocks.PURPUR_PILLAR << 8 | 1},
        {Blocks.PURPUR_SLAB << 8 | 1, Blocks.PURPUR_SLAB << 8 | 1, Blocks.PURPUR_SLAB << 8 | 1, Blocks.PURPUR_SLAB << 8 | 1},
        {Blocks.PURPUR_SLAB << 8 | 0, Blocks.PURPUR_SLAB << 8 | 0, Blocks.PURPUR_SLAB << 8 | 0, Blocks.PURPUR_SLAB << 8 | 0},
        {Blocks.PURPUR_PILLAR << 8 | 1, Blocks.PURPUR_PILLAR << 8 | 2, Blocks.PURPUR_PILLAR << 8 | 1, Blocks.PURPUR_PILLAR << 8 | 2},
        {Blocks.END_ROD << 8 | 3, Blocks.END_ROD << 8 | 4, Blocks.END_ROD << 8 | 5, Blocks.END_ROD << 8 | 2},
        {Blocks.END_ROD << 8 | 5, Blocks.END_ROD << 8 | 2, Blocks.END_ROD << 8 | 3, Blocks.END_ROD << 8 | 4},
        {Blocks.END_ROD << 8 | 4, Blocks.END_ROD << 8 | 5, Blocks.END_ROD << 8 | 2, Blocks.END_ROD << 8 | 3},
        {Blocks.END_ROD << 8 | 2, Blocks.END_ROD << 8 | 3, Blocks.END_ROD << 8 | 4, Blocks.END_ROD << 8 | 5},
        {Blocks.PURPUR_STAIRS << 8 | 33, Blocks.PURPUR_STAIRS << 8 | 34, Blocks.PURPUR_STAIRS << 8 | 35, Blocks.PURPUR_STAIRS << 8 | 32},
        {Blocks.PURPUR_STAIRS << 8 | 25, Blocks.PURPUR_STAIRS << 8 | 26, Blocks.PURPUR_STAIRS << 8 | 27, Blocks.PURPUR_STAIRS << 8 | 24},
        {Blocks.CHEST << 8 | 1, Blocks.CHEST << 8 | 2, Blocks.CHEST << 8 | 3, Blocks.CHEST << 8 | 0},
        {Blocks.CHEST << 8 | 0, Blocks.CHEST << 8 | 1, Blocks.CHEST << 8 | 2, Blocks.CHEST << 8 | 3},
        {Blocks.OBSIDIAN << 8 | 0, Blocks.OBSIDIAN << 8 | 0, Blocks.OBSIDIAN << 8 | 0, Blocks.OBSIDIAN << 8 | 0},
        {Blocks.PURPUR_STAIRS << 8 | 30, Blocks.PURPUR_STAIRS << 8 | 31, Blocks.PURPUR_STAIRS << 8 | 28, Blocks.PURPUR_STAIRS << 8 | 29},
        {Blocks.PURPUR_STAIRS << 8 | 29, Blocks.PURPUR_STAIRS << 8 | 30, Blocks.PURPUR_STAIRS << 8 | 31, Blocks.PURPUR_STAIRS << 8 | 28},
        {Blocks.PURPUR_STAIRS << 8 | 28, Blocks.PURPUR_STAIRS << 8 | 29, Blocks.PURPUR_STAIRS << 8 | 30, Blocks.PURPUR_STAIRS << 8 | 31},
        {Blocks.PURPUR_STAIRS << 8 | 10, Blocks.PURPUR_STAIRS << 8 | 11, Blocks.PURPUR_STAIRS << 8 | 8, Blocks.PURPUR_STAIRS << 8 | 9},
        {Blocks.LADDER << 8 | 0, Blocks.LADDER << 8 | 0, Blocks.LADDER << 8 | 0, Blocks.LADDER << 8 | 0},
        {Blocks.PURPUR_STAIRS << 8 | 18, Blocks.PURPUR_STAIRS << 8 | 19, Blocks.PURPUR_STAIRS << 8 | 16, Blocks.PURPUR_STAIRS << 8 | 17},
        {Blocks.PURPUR_STAIRS << 8 | 11, Blocks.PURPUR_STAIRS << 8 | 8, Blocks.PURPUR_STAIRS << 8 | 9, Blocks.PURPUR_STAIRS << 8 | 10},
        {Blocks.PURPUR_STAIRS << 8 | 17, Blocks.PURPUR_STAIRS << 8 | 18, Blocks.PURPUR_STAIRS << 8 | 19, Blocks.PURPUR_STAIRS << 8 | 16},
        {Blocks.PURPUR_STAIRS << 8 | 27, Blocks.PURPUR_STAIRS << 8 | 24, Blocks.PURPUR_STAIRS << 8 | 25, Blocks.PURPUR_STAIRS << 8 | 26},
        {Blocks.PURPUR_STAIRS << 8 | 31, Blocks.PURPUR_STAIRS << 8 | 28, Blocks.PURPUR_STAIRS << 8 | 29, Blocks.PURPUR_STAIRS << 8 | 30},
        {Blocks.CHEST << 8 | 2, Blocks.CHEST << 8 | 3, Blocks.CHEST << 8 | 0, Blocks.CHEST << 8 | 1},
        {Blocks.BREWING_STAND << 8 | 0, Blocks.BREWING_STAND << 8 | 0, Blocks.BREWING_STAND << 8 | 0, Blocks.BREWING_STAND << 8 | 0},
        {Blocks.DRAGON_HEAD << 8 | 16, Blocks.DRAGON_HEAD << 8 | 17, Blocks.DRAGON_HEAD << 8 | 18, Blocks.DRAGON_HEAD << 8 | 19},
        {Blocks.PURPUR_STAIRS << 8 | 32, Blocks.PURPUR_STAIRS << 8 | 33, Blocks.PURPUR_STAIRS << 8 | 34, Blocks.PURPUR_STAIRS << 8 | 35},
        {Blocks.PURPUR_STAIRS << 8 | 24, Blocks.PURPUR_STAIRS << 8 | 25, Blocks.PURPUR_STAIRS << 8 | 26, Blocks.PURPUR_STAIRS << 8 | 27},
        {Blocks.ENDER_CHEST << 8 | 2, Blocks.ENDER_CHEST << 8 | 3, Blocks.ENDER_CHEST << 8 | 0, Blocks.ENDER_CHEST << 8 | 1},
        {Blocks.LADDER << 8 | 0, Blocks.LADDER << 8 | 0, Blocks.LADDER << 8 | 0, Blocks.LADDER << 8 | 0},
        {Blocks.PURPUR_STAIRS << 8 | 21, Blocks.PURPUR_STAIRS << 8 | 22, Blocks.PURPUR_STAIRS << 8 | 23, Blocks.PURPUR_STAIRS << 8 | 20},
        {Blocks.PURPUR_STAIRS << 8 | 20, Blocks.PURPUR_STAIRS << 8 | 21, Blocks.PURPUR_STAIRS << 8 | 22, Blocks.PURPUR_STAIRS << 8 | 23},
        {Blocks.PURPUR_STAIRS << 8 | 22, Blocks.PURPUR_STAIRS << 8 | 23, Blocks.PURPUR_STAIRS << 8 | 20, Blocks.PURPUR_STAIRS << 8 | 21},
        {Blocks.PURPUR_STAIRS << 8 | 23, Blocks.PURPUR_STAIRS << 8 | 20, Blocks.PURPUR_STAIRS << 8 | 21, Blocks.PURPUR_STAIRS << 8 | 22},
        {Blocks.MAGENTA_WALL_BANNER << 8 | 3, Blocks.MAGENTA_WALL_BANNER << 8 | 0, Blocks.MAGENTA_WALL_BANNER << 8 | 1, Blocks.MAGENTA_WALL_BANNER << 8 | 2},
        {Blocks.MAGENTA_WALL_BANNER << 8 | 0, Blocks.MAGENTA_WALL_BANNER << 8 | 1, Blocks.MAGENTA_WALL_BANNER << 8 | 2, Blocks.MAGENTA_WALL_BANNER << 8 | 3},
        {Blocks.MAGENTA_WALL_BANNER << 8 | 2, Blocks.MAGENTA_WALL_BANNER << 8 | 3, Blocks.MAGENTA_WALL_BANNER << 8 | 0, Blocks.MAGENTA_WALL_BANNER << 8 | 1},
        {Blocks.MAGENTA_WALL_BANNER << 8 | 1, Blocks.MAGENTA_WALL_BANNER << 8 | 2, Blocks.MAGENTA_WALL_BANNER << 8 | 3, Blocks.MAGENTA_WALL_BANNER << 8 | 0},
    };

    /** 데이터 표지 한 개(템플릿 좌표, metadata). */
    public record Marker(int x, int y, int z, String metadata) {
    }

    /** 템플릿 한 벌. */
    public record Template(String name, int sizeX, int sizeY, int sizeZ, byte[] grid, List<Marker> markers) {
        public int stateAt(int x, int y, int z) {
            return Byte.toUnsignedInt(grid[(y * sizeZ + z) * sizeX + x]);
        }
    }

    private static Template template(String name, int sx, int sy, int sz, String grid, Marker... markers) {
        byte[] bytes = Base64.getDecoder().decode(grid);
        if (bytes.length != sx * sy * sz) throw new IllegalStateException("end city template size " + name);
        return new Template(name, sx, sy, sz, bytes, List.of(markers));
    }

    /** 이름순 템플릿 표. */
    public static final List<Template> TEMPLATES = List.of(
            template("base_floor", 10, 4, 10,
                    "BAQEBAQEBAQEBAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQAAAAAAAAAAAQEAAAAAAAAAAAEBAAAAAAAAAAABAQA" +
                    "AAAAAAAAAAQEAAAAAAAAAAAEBAQFAAAAAAUEBAQEBAQEBAQEBAQEAQICAgICAgEEBAIEBAQEBAQCBAQCBAQEBAQEAgQEAgQE" +
                    "BAQEBAIEBAIEBAQEBAQCBAQCBAQEBAQEAgQEAgQEBAQEBAIEBAECAgQEAgIBBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAECAwIC" +
                    "AwIBBAQCBAQEBAQEAgQEAwQEBAQEBAMEBAIEBAQEBAQCBAQCBAQEBAQEAgQEAwQEBAQEBAMEBAIEBAQEBAQCBAQBAgIEBAIC" +
                    "AQQEBAQGBAQGBAQEBAQEBAQEBAQEBAQBAgMCAgMCAQQEAgQEBAQEBAIEBAMEBAQEBAQDBAQCBAQEBAQEAgQEAgQEBAQEBAIE" +
                    "BAMEBAQEBAQDBAQCBAQEBAQEAgQEAQICBAQCAgEEBAQEBAQEBAQEBA==",
                    new Marker(3, 2, 9, "Sentry"),
                    new Marker(6, 2, 9, "Sentry")
            ),
            template("base_roof", 12, 2, 12,
                    "BwsNDQsNDQsNDQsOCAAAAAAAAAAAAAAPCQAAAAAAAAAAAAAQCQAAAAAAAAAAAAAQCAAAAAAAAAAAAAAPCQAAAAAAAAAAAAAQ" +
                    "CQAAAAAAAAAAAAAQCAAAAAAAAAAAAAAPCQAAAAAAAAAAAAAQCQAAAAAAAAAAAAAQCAAAAAAAAAAAAAAPCgwFBQwFBQwFBQwR" +
                    "BAQEBAQEBAQEBAQEBBIEBAQEBAQEBBIEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBBIEBAQEBAQEBBIEBAQEBAQEBAQEBAQE"
            ),
            template("bridge_end", 5, 6, 2,
                    "BAQTBAQEAAAABAANDQ0AAAAAAAAABAQEAAAEBAQAEgQEBBIABAQEAAQEBAQEABQEFAAEBAQEBBUAAAAV"
            ),
            template("bridge_gentle_stairs", 5, 7, 8,
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBBMEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQECAAAAA8EBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAAAAA8AAAAAAAAVFRUABAQEBAQEBAQEBAQEBAQECAAAAA8AAAAA" +
                    "AAAVFRUACQQEBBAJBAQEEAQEEwQECAAAAA8AAAAAAAAVFRUACQQEBBAJBAQEEAQEBAQEBAQEBAQAAAAAAAAVFRUACQQEBBAJ" +
                    "BAQEEAQEBAQEBAQEBAQEBAQEBAQEBAQEAAQEBAAJBAQEEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBA=="
            ),
            template("bridge_piece", 5, 6, 4,
                    "BAgTDwQEBBMEBAQEEwQEBAQTBAQIAAAADwAAAAAAAAAAAAAAAAAAAAAEBAQACQQEBBAJBAQEEAkEBAQQBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE"
            ),
            template("bridge_steep_stairs", 5, 7, 4,
                    "BAQEBAQEBAQEBAQEBAQEBAQTBAQEBAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAQEBAQECAAPBAAFBQUABAQEBAQECAAPBAAF" +
                    "BQUACQQEBBAECBMPBAAFBQUACQQEBBAEBAQEBAAFBQUACQQEBBAEBAQEBAQEBAQEAAQEBAAEBAQEBAQEBAQEBAQEBAQ="
            ),
            template("fat_tower_base", 13, 4, 13,
                    "BAQEBAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAQAAAAAAAAABAQEBAQAAAAAAAAAAAAEBAQEAAAAAAAAAAAABAQEAAAAAAQE" +
                    "BAAAAAAEBAAAAAAEBAQAAAAABAQAAAAABBUEAAAAAAQEBAAAAAAAAAAAAAQEBAQAAAAAAAAAAAAEBAQEBAAAAAAAAAAEBAQE" +
                    "BAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEBAQQEBAQEBAQEAQEEBAQBAQQEBAQEAQQEBAQE" +
                    "BAQBBAQEBAEEBAQEBAQEAQQEBAEVBAQEBAQEBAQBBAQBBAQEBAQEBAQEAQQEAQQEBAQEBAQEFQEEBAQBBAQEBAQEBAEEBAQE" +
                    "AQQEBAQEBAQBBAQEBAQBAQQEBAEBBAQEBAQEBAQBAQEEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQLBAQEBAQEBAQEBAQBEwEE" +
                    "BAQEBAQEBAEBBAQEAQEEBAQEBAEEBAQEBAQEAQQEBAQBFwQEBAQEBAEEBAQBBAQEBAQEBAQEAQQIFgQEBAQEBAQEBBYPBAEE" +
                    "BAQEBAQEBAQBBAQEAQQEBAQEBBgBBAQEBAEEBAQEBAQEAQQEBAQEAQEEBAQBAQQEBAQEBAQEARMBBAQEBAQEBAQEBAQMBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEAQEBBAQEBAQEBAQBAQQEBAEBBAQEBAQBBBkEBAQEBAEEBAQEAQQEBAQEBAQBBAQEAQQE" +
                    "BAQEBAQEBAEEBAEEBAQEBAQEBAQBBAQBBAQEBAQEBAQEAQQEBAEEBAQEBAQEAQQEBAQBBAQEBAQaBAEEBAQEBAEBBAQEAQEE" +
                    "BAQEBAQEBAEBAQQEBAQEBAQEBAQEBAQEBAQEBA=="
            ),
            template("fat_tower_middle", 13, 8, 13,
                    "BAQEBAQEBAQEBAQEBAQEBAQEAAAABAQEBAQEBAQAABUEBAAABAQEBAQABAQEBAQEBAAEBAQEAAQEBAQEBAQABAQEAAQEBAQE" +
                    "BAQEBAAEBAAEBAQEBAQEBAQABAQABAQEBAQEBAQEAAQEBAAEBAQEBAQEAAQEBAQABAQEBAQEBAAEBAQEBAAABAQVAAAEBAQE" +
                    "BAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEBAQQEBAQEBAQEAQEEBBUBAQQEBAQEAQQEBAQE" +
                    "BAQBBAQEBAEEBAQEBAQEAQQEBAEEBAQEBAQEBAQBBAQBBAQEBAQEBAQEAQQEAQQEBAQEBAQEBAEEBAQBBAQEBAQEBAEEBAQE" +
                    "AQQEBAQEBAQBBAQEBAQBARUEBAEBBAQEBAQEBAQBAQEEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQLBAQEBAQEBAQEBAQBEwEE" +
                    "BAQEBAQEBAEBBAQEAQEEBAQEBAEEBAQEBBkEAQQEBAQBBAQEBAQEBAEEBAQBBAQEBAQEBAQEAQQIFgYEBAQEBAQEBhYPBAEE" +
                    "BAQEBAQEBAQBBAQEAQQEBAQEBAQBBAQEBAEEGgQEBAQEAQQEBAQEAQEEBAQBAQQEBAQEBAQEARMBBAQEBAQEBAQEBAQMBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEAQEBBAQEBAQEBAQBAQQEBAEBBAQEBAQBBAQEBAQEBAEEBAQEAQQEBAQEBBgBBAQEAQQE" +
                    "BAQEBAQEBAEEBAEEBAQEBAQEBAQBBAQBBAQEBAQEBAQEAQQEBAEXBAQEBAQEAQQEBAQBBAQEBAQEBAEEBAQEBAEBBAQEAQEE" +
                    "BAQEBAQEBAEBAQQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQEAAAEBAQAAAQEBAQEAAQE" +
                    "BAQEBAQABAQEBAAEBAQEBAQEAAQEBAAEBAQEBAQEBBUABAQABAQEBAQEBAQEAAQEABUEBAQEBAQEBAAEBAQABAQEBAQEBAAE" +
                    "BAQEAAQEBAQEBAQABAQEBAQAAAQEBAAABAQEBAQEBAQAAAAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQB" +
                    "AQEEBAQEBAQEBAEBBAQEAQEEBAQEBAEEBAQEBAQEAQQEBAQBBAQEBAQEBAEEBAQBFQQEBAQEBAQEAQQEAQQEBAQEBAQEBAEE" +
                    "BAEEBAQEBAQEBBUBBAQEAQQEBAQEBAQBBAQEBAEEBAQEBAQEAQQEBAQEAQEEBAQBAQQEBAQEBAQEAQEBBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQECwQEBAQEBAQEBAQEARMBBAQEBAQEBAQBAQQGBAEBBAQEBAQBBAQEBAQEBAEEBAQEARcEBAQEBAQBBAQE" +
                    "AQQEBAQEBAQEBAEECBYEBAQEBAQEBAQWDwQBBAQEBAQEBAQEAQQEBAEEBAQEBAQYAQQEBAQBBAQEBAQEBAEEBAQEBAEBBAYE" +
                    "AQEEBAQEBAQEBAETAQQEBAQEBAQEBAQEDAQEBAQEBAQEBAQEBBMEBAQEBAQEBAQEBAAAAAQEBAQEBAQEAQEEBAQBAQQEBAQE" +
                    "AQQZBAQEBAQBBAQEBAEEBAQEBAQEAQQEBAAEBAQEBAQEBAQBBBYABAQEBAQEBAQEAQQEAAQEBAQEBAQEBAEEBAQBBAQEBAQE" +
                    "BAEEBAQEAQQEBAQEGgQBBAQEBAQBAQQEBAEBBAQEBAQEBAQBAQEEBAQEBAQEBAQEBAQEBAQEBAQ=",
                    new Marker(2, 2, 6, "Sentry"),
                    new Marker(10, 2, 6, "Sentry"),
                    new Marker(6, 6, 2, "Sentry"),
                    new Marker(6, 6, 10, "Sentry")
            ),
            template("fat_tower_top", 17, 6, 17,
                    "BAQEBAQEBAQEBAQEBAQEBAQEBwsNDQsLDQ0NCwsNDQsOBAQIAAAAAAAAAAAAAAAAAA8EBAkAAAAAAAAAAAAAAAAAEAQECQAA" +
                    "AAAAFQQAAAAAAAAQBAQIAAAABAQEBAAAAAAAAA8EBAgAAAAEBAQEAAAAAAAADwQECQAABAQEBAQAAAAAAAAQBAQJAAAEBAQE" +
                    "BAQEBAQAABAEBAkAAAAAAAAEBAQEBAAAEAQECAAAAAAAAAQEBAQAAAAPBAQIAAAAAAAABAQEBAAAAA8EBAkAAAAAAAAEFQAA" +
                    "AAAAEAQECQAAAAAAAAAAAAAAAAAQBAQIAAAAAAAAAAAAAAAAAA8EBAoMBQUMDAUFBQwMBQUMEQQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBBIEBAQEBAQEBAQEBAQEEgQEBAECAgICAgICAgICAgEEBAQEAgQEBAQVABQEBAQEAgQEBAQC" +
                    "BAQEBAQEBAQEBAQCBAQEBAIEBAQEBAQEBAQEBAIEBAQEAgQEBAQEBAQEBAQEAgQEBAQCBAQEBAQEAQQEBAQCBAQEBAIEBAQE" +
                    "BAQEBAQEBAIEBAQEAgQEBAQBBAQEBAQEAgQEBAQCBAQEBAQEBAQEBAQCBAQEBAIdBAQEBAQEBAQEBAIEBAQEAgQEBAQEBAQE" +
                    "BAQEAgQEBAQCBAQeBAQEBAQEBAQCBAQEBAECAgICAgICAgICAgEEBAQSBAQEBAQEBAQEBAQEBBIEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQBAgMCAgMCAgICAgIBBAQEBAIEBAQEBAQVABQEBAIEBAQE" +
                    "AwQEBAQEBAQEBAQEAgQEBAQCBAQEBAQEBAQEBAQCBAQEBAIEBAQEBAQEBAQEBAIEBAQEAwQEBAQEBAEEBAQEAwQEBAQCBAQE" +
                    "BAQEBAQEBAQCBAQEBAMEBAQEAQQEBAQEBAMEBAQEAgQEBAQEBAQEBAQEAgQEBAQCBgQEBAQEBAQEBAQCBAQEBAMEBAQEBAQE" +
                    "BAQEBAMEBAQEAgQEBgQEBAQEBAQEAgQEBAQBAgMCAgMCAwICAwIBBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAQIDAgIDAgICAgICAQQEBAQCBAQEBAQEBAQVABQCBAQE" +
                    "BAMEBAQEBAQEBAQEBAIEBAQEAgQEBAQEBAQEBAQEAgQEBAQCBAQEBAQEBAQEBAQCBAQEBAMEBAQEBAQBBAQEBAMEBAQEAgQE" +
                    "BAQEBAQEBAQEAgQEBAQDBAQEBAEEBAQEBAQDBAQEBAIEBAQEBAQEBAQEBAIEBAQEAgQEBAQEBAQEBAQEAgQEBAQDBAQEBAQE" +
                    "BAQEBAQDBAQEBAIEBAQEBAQEBAQEBAIEBAQEAQIDAgIDAgMCAgMCAQQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAcLDQ0LCw0NCw0NCwsNDQsOCAAAAAAAAAAAAAAAAAAAAA8JAAAAAAAAAAAAAAAAAAAAEAkAAAAAAAAABAQEBAQVAAAQ" +
                    "CAAAAAAAAAAAAAAAAAAAAA8IAAAAAAAAAAAAAAAAAAAADwkAAAAAAAAAAAAAAAAAAAAQCQAAAAAAAAAAAAAAAAAAABAIAAAA" +
                    "AAAAAAAAAAAAAAAADwkAAAAAAAAAAAAAAAAAAAAQCQAAAAAAAAAAAAAAAAAAABAIAAAAAAAAAAAAAAAAAAAADwgAAAAAAAAA" +
                    "AAAAAAAAAAAPCQAAAAAAAAAAAAAAAAAAABAJAAAAAAAAAAAAAAAAAAAAEAgAAAAAAAAAAAAAAAAAAAAPCgwFBQwMBQUMBQUM" +
                    "DAUFDBEEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBBsNDQ0NBAQEBAQEBAQEBAQECQQEBAQEBAQE" +
                    "BAQEBAQEBAQcBQUFBQQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQE",
                    new Marker(3, 2, 11, "Chest"),
                    new Marker(5, 2, 13, "Chest")
            ),
            template("second_floor_1", 12, 8, 12,
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQUBAQEBAQEBAQEBAQABAQEBAQEBAQEBAQVBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAIEBAIEBAQEBAQEBAQEFAAVBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAIEBAIEBAQEBAQEBBQAFQQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BwsNCwsNDQsLDQsOCAAAAAAAAAAAAAAPCQAAAAAAAAAAAAAQCAAAABUEBAQEAAAPCAAAAAAAAAAEAAAPCQAAAAAAAAAEAAAQ" +
                    "CQAAAAAAAAAEAAAQCAAAAAAAAAAAAAAPCAAAAAAAAAAAAAAPCQAAAAAAAAAAAAAQCAAAAAAAAAAAAAAPCgwFDAwFBQwMBQwR" +
                    "EgQEBAQEBAQEBAQSBAECAgICAgICAgEEBAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIE" +
                    "BAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIEBAECAgICAgICAgEEEgQEBAQEBAQEBAQS" +
                    "BAQEBAQEBAQEBAQEBAECAwICAgIDAgEEBAIEBAQEBAQEBAIEBAMEBAQEBAQEBAMEBAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIE" +
                    "BAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIEBAMEBAQEBAQEBAMEBAIEBAQEBAQEBAIEBAECAwICAgIDAgEEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAECAwICAgIDAgEEBAIEBAQEBAQEBAIEBAMEBAQEBAQEBAMEBAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIE" +
                    "BAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIEBAMEBAQEBAQEBAMEBAIEBAQEBAQEBAIEBAECAwICAgIDAgEEBAQEBAQEBAQEBAQE"
            ),
            template("second_floor_2", 12, 8, 12,
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAQEBAQE" +
                    "BAQEBAQABQQEBAQEBAQEBAQEFQQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAEBUEBAQE" +
                    "BAQEBAQABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQVBAQEBAQEBAQEBAQNBAQEBAQE" +
                    "BAQEBBQABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BwsNCwsNDQsLDQsOCAAAAAAAAAAAAAAPCQAAAAAAAAAAAAAQCAAABAQEBAQEAAAPCAAABAQEBAQEAAAPCQAABAQEBAQEAAAQ" +
                    "CQAABAQJFBQUAAAQCAAABAQEBAQEAAAPCAAABAQEBAQEAAAPCQAAAAAAAAAAAAAQCAAAAAAAAAAAAAAPCgwFDAwFBQwMBQwR" +
                    "EgQEBAQEBAQEBAQSBAECAgICAgICAgEEBAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIE" +
                    "BAIEBAQEBAQGBAIEBAIEBAQEBAQECAIEBAIEBAQEBAQECAIEBAIEBAQEBAQEBAIEBAECAgICAgICAgEEEgQEBAQEBAQEBAQS" +
                    "BAQEBAQEBAQEBAQEBAECAwICAgIDAgEEBAIEBAQEBAQEBAIEBAMEBAQEBAQEBAMEBAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIE" +
                    "BAIEBAQEBAQEBAIEBAIEBAQEBAQECQIEBAMEBAQEBAQECQIEBAIEBAQEBAQEBAIEBAECAwICAgIDAgEEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAECAwICAgIDAgEEBAIEBAQEBAQEBAIEBAMEBAQEBAQEBAMEBAIEBAQEBAQEBAIEBAIEBAQEBAQEBAIE" +
                    "BAIEBAQEBAQEBAIEBAIEBAQEBAQUCAIEBAMEBAQEBAQUCAIEBAIEBAQEBAQEBAIEBAECAwICAgIDAgEEBAQEBAQEBAQEBAQE",
                    new Marker(8, 5, 6, "Sentry")
            ),
            template("second_roof", 14, 2, 14,
                    "BwsNDQsLDQ0LCw0NCw4IAAAAAAAAAAAAAAAADwkAAAAAAAAAAAAAAAAQCQAAAAAAAAAAAAAAABAIAAAAAAAAAAAAAAAADwgA" +
                    "AAAAAAAAAAAAAAAPCQAAAAAAAAAAAAAAABAJAAAAAAAAAAAAAAAAEAgAAAAAAAAAAAAAAAAPCAAAAAAAAAAAAAAAAA8JAAAA" +
                    "AAAAAAAAAAAAEAkAAAAAAAAAAAAAAAAQCAAAAAAAAAAAAAAAAA8KDAUFDAwFBQwMBQUMEQQEBAQEBAQEBAQEBAQEBBIEBAQE" +
                    "BAQEBAQEEgQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQSBAQEBAQEBAQEBBIEBAQEBAQEBAQEBAQEBAQ="
            ),
            template("ship", 13, 24, 29,
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQTBAQEBAQEBAQEBAQEEwQEBAQEBAQEBAQEBBMEBAQEBAQEBAQEBAQTBAQEBAQEBAQEBAQEEwQEBAQEBAQEBAQEBBME" +
                    "BAQEBAQEBAQEBAQTBAQEBAQEBAQEBAQEEwQEBAQEBAQEBAQEBBMEBAQEBAQEBAQEBAQTBAQEBAQEBAQEBAQEEwQEBAQEBAQE" +
                    "BAQEBBMEBAQEBAQEBAQEBAQTBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBBMEBAQEBAQEBAQEBAQTBAQE" +
                    "BAQEBAQEBAQEEwQEBAQEBAQEBAQEBBMEBAQEBAQEBAQEBAAAAAQEBAQEBAQEBAgAAAAPBAQEBAQEBAQEAAAABAQEBAQEBAQE" +
                    "BAAAAAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQIAAAADwQEBAQEBAQEBAAAAAQEBAQEBAQEBAQAAAAEBAQEBAQEBAQEAAAABAQE" +
                    "BAQEBAQECAAAAA8EBAQEBAQEBAQAAAAEBAQEBAQEBAQEABMABAQEBAQEBAQEBAATAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBBMEBAQEBAQEBAQEBAQTBAQEBAQEBAQEBAQA" +
                    "EwAEBAQEBAQEBAQEABMABAQEBAQEBAQEAAATAAAEBAQEBAQEBAAAEwAABAQEBAQEBAQAHxMfAAQEBAQEBAQIAB8THwAPBAQE" +
                    "BAQEBAAfAR8ABAQEBAQEBAQAHxMfAAQEBAQEBAQEAB8THwAEBAQEBAQECAAfEx8ADwQEBAQEBAQAHxMfAAQEBAQEBAQEAB8T" +
                    "HwAEBAQEBAQEBAAfEx8ABAQEBAQEBAgAHxMfAA8EBAQEBAQEAB8THwAEBAQEBAQEBAAfEx8ABAQEBAQEBAQAHxMfAAQEBAQE" +
                    "BAQIAAATAAAPBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQTBAQEBAQEBAQEBAQEEwQEBAQEBAQE" +
                    "BAQEAAAABAQEBAQEBAQEAAAAAAAEBAQEBAQEBAAEBAQABAQEBAQEBAAEBAQEBAAEBAQEBAQABAQEBAQABAQEBAQEAAQEBAQE" +
                    "AAQEBAQECAAEBAQEBAAPBAQEBAQABAQBBAQABAQEBAQEAAQEBAQNAAQEBAQEBAAEBAQEAAAEBAQEBAgABAQEBAAADwQEBAQE" +
                    "AAQEBAQAAAQEBAQEBAAEBAQEAAAEBAQEBAQABAQEBAAABAQEBAQIAAQEBAQAAA8EBAQEBAAEBAQEAAAEBAQEBAQABAQEBAAA" +
                    "BAQEBAQEAAQEBAQAAAQEBAQECAAAAAAAAAAPBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAEBAQE" +
                    "BAQEBAQEBAAAAAQEBAQEBAQEBAAqBCoABAQEBAQEBAQABAYEAAQEBAQEBAQABAQEBAQABAQEBAQEAAQEBAQEAAQEBAQEAAQE" +
                    "BAQEBAQABAQEBAAEBAQEBAQEAAQEBAQABAQEBAQEBAAEBAQEAAQEBAEEBAQABAQEBAAEBAQEBAQEAAQEBAQABAQEBAQEBAAE" +
                    "BAQEAAQEBAQEBAQABAQEBAAEBAQEBAQEAAQEBAQABAQEBAQNDQAEBAQEAAQEBAQEAAAABAQEBAAEBAQEBAAAAAQEBAQABAQE" +
                    "BAQAAAAEBAQEAAQEBAQEAAAABAQEBAAEBAQEBAAAAAQEBAQAAAAAAAAAAAAEBAQEDAQEBAwEBAQMBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQT" +
                    "BAQEBAQEBAQEBAQEEwQEBAQEBAQEBAQEAAAABAQEBAQEBAQEAAYGBgAEBAQEBAQEBAAEBAQABAQEBAQEBAAEBAQEBAAEBAQE" +
                    "BAQABAQEBAQABAQEBAQABAQEBAQEBAAEBAQEAAQEBAQEBAQABAQECAAEBAQEBAQEAA8EBAQABAQEAQQEBAAEBAQEAAQEBAQE" +
                    "BAQABAQECAAEBAQEBAQEAA8EBAQABAQEBAQEBAAEBAQEAAQEBAQEBAQABAQEBAAEBAQEBAQEAAQEBCAAAAAAAAANDQAOBAQI" +
                    "AAAAAAAAAAAADwQECQAAAAAAAAAAABAEBAgAAAAAAAAAAAAPBAQIAAAAAAAAAAAADwQECQAAAAAAAAAAABAEBAgAAAAAAAAA" +
                    "AAAPBAQhDAUMDAUMDAwMIgQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEEwQEBAQEBAQEBAQEBBMEBAQEBAQEBAQEBAQABAQEBAQEBAQEBAQAGQAEBAQEBAQEBAQABAQEAAQEBAQEBAQEAAQEBAAE" +
                    "BAQEBAQEAAQEBAQEAAQEBAQEBAAEBAQEBAAEBAQEBAAEBAQEBAQEAAQEBAQABAQEBAQEBAAEBAQEBAQEBAQEBAQEBAQEBAAE" +
                    "BAQBBAQEAAQEBAQABAQEBAQEBAAEBAQEBAQEBAQEBAQEBAQEBAAEBAQEBAQEAAQEBAQABAQEBAQEBAAEBAQEAAAAAAAABAQA" +
                    "BAQEBAAABQUAAAQEAAQEBAQBAAQEAAAEBAEEBAQEAgQEBAQEBAQCBAQEBAIEBAQEBAQEAgQEBAQCBAQEBAQEBAIEBAQEAgQE" +
                    "BAEEBAQCBAQEBAECAgIBAgICAQQEBBIEBAQEBAQGBAQSBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEEwQEBAQE" +
                    "BAQEBAQEBBMEBAQEBAQEBAQEBAQTBAQEBAQEBAQEBAQEEwQEBAQEBAQEBAQEAAAABAQEBAQEBAQEAAAAAAAEBAQEBAQEBAAA" +
                    "AAAABAQEBAQEBAAAAAAAAAAEBAQEBAQAAAAAAAAABAQEBAQAAAAAAAAAAAAEBAQEAAAAAAAAAAAABAQEBAAAAAATAAAAAAQE" +
                    "BAQAAAAAAwAAAAAEBAQEAAAAAAEAAAAABAQEBAAAAAAAAAAAAAQEBAQAAAAAAAAAAAAEBAQEAAAAAAAAAAAABAQEBAAAAAAA" +
                    "AAAAAAQEBAQAAAUFAAAEBAAEBAQEAAAEBAAABAQABAQEBAEABAQAAAQEAQQEBAQCBAQEBAQEBAIEBAQEAwQEBAQEBAQDBAQE" +
                    "BAMEBAQEBAQEAwQEBAQCBAQEKwQEBAIEBAQEAQIDAgECAwIBBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBCwE" +
                    "BAQEBAQEBAQEBAQFBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQABAQEBAQEBAQEBAQABAAEBAQEBAQE" +
                    "BAQABAQEAAQEBAQEBAQECQQEBBAEBAQEBAQEACMEBAQlAAQEBAQEBAkEBAQEBBAEBAQEBAAjBAQTBAQlAAQEBAQJBAQEEwQE" +
                    "BBAEBAQECQQEBAUEBAQQBAQEBAAEBAQEBAQEAAQEBAQJBAQEAQQEBBAEBAQECQQEBCQEBAQQBAQEBAAEBAQEBAQEAAQEBAQJ" +
                    "BAQEBAQEBBAEBAQECQQEBAQEBAQQBAQEBAAEBAQEBA0NAAQEBAQABAQEBAQAAAAEBAQEAQAEBAAADAwBBAQEBAIEBAQEBAQE" +
                    "AgQEBAQCBAQEBAQEBAIEBAQEAgQEBAQEBAQCBAQEBAIEBAQEBAQEAgQEBAQBAgICAQICAgEEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBBIEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQTBAQEBAQEBAQEBAQEEwQEBAQEBAQEEgQE" +
                    "BAUEBAQSBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQBBAQEBAQEBAQEBAQEJAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAcLCwsEBAQEBAQECw4IAAAABAQAAA0NAAAPCQAAAAAA" +
                    "AAAAAAAAEAkAAAAAAAAAAAAAABAIAAAAAAAAAAAAAAAPCAAAAAAAAAAAAAAADwkAAAAAAAAAAAAAABAJAAAAAAAAAAAAAAAQ" +
                    "CAAAAAAAAAAAAAAADwoMBQUMDAUMDAUFDBEEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQTBAQEBAQEBAQEBAQEEwQEBAQEBAQEBAQEBAUEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEE" +
                    "BAQEBAQEBAQEBAQkBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQA" +
                    "DQAEBAAABAQAAAQECQQmDQ0nBAQEBBAEBAkEBAEEBAQEBAQQBAQJBAQEBAQEBAQEEAQECQQEBAQEBAQEBBAEBAkEBAQEBAQE" +
                    "BAQQBAQJBAQbDQ0NKAQEEAQEAAUFAAUFBQAFBQAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQTBAQEBAQEBAQEBAQEEwQEBAQEBAQEBAQEBAUEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEAQQEBAQEBAQEBAQEBCQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQGBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBBQEBAQEBAQEBAQEBAQTBAQEBAQEBAQEBAQEEwQEBAQEBAQEBAQEBAUEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQBBAQEBAQEBAQEBAQEJAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEEBAQEBAQEBAQEBAQkBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAQQEBAQE" +
                    "BAQEBAQEBCQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQBBAQEBAQEBAQEBAQEJAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEEBAQEBAQEBAQEBAQkBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAQQEBAQEBAQEBAQEBCQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQBBAQEBAQEBAQE" +
                    "BAQEJAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAEEBAQEBAQEBAQEBAQkBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBBQEFAQEBAQEBAQEBAQUARQEBAQEBAQEBAQEFCQUBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBCALCwspBAQEBAQEBAQIBAQEDwQEBAQEBAQECAQBBA8EBAQEBAQEBAgEJAQPBAQEBAQEBAQhDAwMIgQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAEEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE",
                    new Marker(6, 4, 8, "Sentry"),
                    new Marker(5, 5, 7, "Chest"),
                    new Marker(6, 5, 7, "Elytra"),
                    new Marker(7, 5, 7, "Chest"),
                    new Marker(8, 6, 27, "Sentry"),
                    new Marker(4, 11, 27, "Sentry")
            ),
            template("third_floor_1", 14, 8, 14,
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEFQAUBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEFQAUBAQEBAQEBAQEBAQEBAQEAgQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEFQAUBAQEBAQEBAQEBAQEBAIEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAcLDQ0LCw0N" +
                    "CwsNDQsOCAAAAAAAAAAAAAAAAA8JAAAAAAAAAAAAAAAAEAkAAAAAAAAAAAAAAAAQCAAAAAAAAAAAAAAAAA8IAAAAAAAAAAAA" +
                    "AAAADwkAAAAAAAAAAAAAAAAQCQAAAAAAAAAAAAAAABAIAAAAAAAAAAAAAAAADwgAAAAAAAAAAAAAAAAPCQAABAQEBAQEFQAA" +
                    "ABAJAAAAAAAAAAAAAAAAEAgAAAAAAAAAAAAAAAAPCgwFBQwMBQUMDAUFDBESBAQEBAQEBAQEBAQEEgQBAgICAgICAgICAgEE" +
                    "BAIEBAQECRAEBAQEAgQEAgQEBAQJEAQEBAQCBAQCBAQEBAkQBAQEBAIEBAIEBAQECRAEBAQEAgQEAgQEBAQBAQQEBAQCBAQC" +
                    "BAQEBAkQBAQEBAIEBAIEBAQELS4EBAQEAgQEAgQEBAQEBAQEBAQCBAQCBAQEBAQEBAQEBAIEBAIEBAQEBAQEBAQEAgQEAQIC" +
                    "AgICAgICAgIBBBIEBAQEBAQEBAQEBAQSBAQEBAQEBAQEBAQEBAQEAQIDAgMCAgMCAwIBBAQCBAQEBAQEBAQEBAIEBAMEBAQE" +
                    "BAQEBAQEAwQEAgQEBAQEBAQEBAQCBAQDBAQEBAQEBAQEBAMEBAIEBAQEAQEEBAQEAgQEAgQEBAQEBAQEBAQCBAQDBAQEBAQE" +
                    "BAQEBAMEBAIEBAQEBAQEBAQEAgQEAwQEBAQEBAQEBAQDBAQCBAQEBAQEBAQEBAIEBAECAwIDAgIDAgMCAQQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAECAwIDAgIDAgMCAQQEAgQEBAQEBAQEBAQCBAQDBAQEBAQEBAQEBAMEBAIEBAQEBAQEBAQE" +
                    "AgQEAwQEBAQEBAQEBAQDBAQCBAQEBAEBBAQEBAIEBAIEBAQEBAQEBAQEAgQEAwQEBAQEBAQEBAQDBAQCBAQEBAQEBAQEBAIE" +
                    "BAMEBAQEBAQEBAQEAwQEAgQEBAQEBAQEBAQCBAQBAgMCAwICAwIDAgEEBAQEBAQEBAQEBAQEBAQ="
            ),
            template("third_floor_2", 14, 8, 14,
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAQEBAQEBAQEBAQE" +
                    "BAQAAAAABAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQJAAAEBAQEBAQEBAQEBAQEAAAAAAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAkABAQEBAQEBAQEBAQEBAAAAAAEBAQEBAQEBAQEBAQEAgQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAkABAQEBAQEBAQEBAQEBAIEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAcLDQ0LCw0N" +
                    "CwsNDQsOCAAAAAAAAAAAAAAAAA8JAAAAAAAAAAAAAAAAEAkAAAQEBAAABAQEAAAQCAAABAQEGRkEBAQAAA8IAAAEBAQEBAQE" +
                    "BAAADwkAAAQEBAQEBAQEAAAQCQAABAQEBAQEBAQAABAIAAAEBAAAAAAEBAAADwgAAAQEBAQEBAQEAAAPCQAABAQEBAQECQAA" +
                    "ABAJAAAAAAAAAAAAAAAAEAgAAAAAAAAAAAAAAAAPCgwFBQwMBQUMDAUFDBESBAQEBAQEBAQEBAQEEgQBAgICAgICAgICAgEE" +
                    "BAIGBAQEKi8EBAQGAgQEAgQEBAQEBAQEBAQCBAQCBAQEBAQEBAQEBAIEBAIEBAQEBAQEBAQEAgQEAgAEBAQEBAQEBAACBAQC" +
                    "BAQEBAQEBAQEBAIEBAIABAQABAQABAQAAgQEAgQEBAQEBAQEBAQCBAQCAAQEBAQEBAQEAAIEBAIEBAQEBAQEBAQEAgQEAQIC" +
                    "AgICAgICAgIBBBIEBAQEBAQEBAQEBAQSBAQEBAQEBAQEBAQEBAQEAQIDAgMCAgMCAwIBBAQCBAQEBAYEBAQEBAIEBAMEBAQE" +
                    "BAQEBAQEAwQEAgQEBAQEBAQEBAQCBAQDBAQEBAQEBAQEBAMEBAIABAQEBAQEBAQAAgQEAgQEBAQEBAQEBAQCBAQCAAAAAAQE" +
                    "AAAAAAIEBAIEBAQEBAQEBAQEAgQEAgAEBAQEBAQEBAACBAQCBAQEBAQEBAQEBAIEBAECAwIDAgIDAgMCAQQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAECAwIDAgIDAgMCAQQEAgQEBAQEBAQEBAQCBAQDBAQEBAQEBAQEBAMEBAIEBAQEBAQEBAQE" +
                    "AgQEAwQEBAQEBAQEBAQDBAQCAAQEBAQEBAQEAAIEBAIEBAQEBAQEBAQEAgQEAgAEBAQEBAQEBAACBAQCBAQEBAQEBAQEBAIE" +
                    "BAIABAQEBAQEBAQAAgQEAgQEBAQEBAQEBAQCBAQBAgMCAwICAwIDAgEEBAQEBAQEBAQEBAQEBAQ=",
                    new Marker(2, 5, 2, "Sentry"),
                    new Marker(11, 5, 2, "Sentry"),
                    new Marker(6, 6, 2, "Chest")
            ),
            template("third_roof", 16, 2, 16,
                    "BwsNDQsLDQsLDQsLDQ0LKQgAAAAAAAAAAAAAAAAAAA8JAAAAAAAAAAAAAAAAAAAQCQAAAAAAAAAAAAAAAAAAEAgAAAAAAAAA" +
                    "AAAAAAAAAA8IAAAAAAAAAAAAAAAAAAAPCQAAAAAAAAAAAAAAAAAAEAgAAAAAAAAAAAAAAAAAAA8IAAAAAAAAAAAAAAAAAAAP" +
                    "CQAAAAAAAAAAAAAAAAAAEAgAAAAAAAAAAAAAAAAAAA8IAAAAAAAAAAAAAAAAAAAPCQAAAAAAAAAAAAAAAAAAEAkAAAAAAAAA" +
                    "AAAAAAAAABAIAAAAAAAAAAAAAAAAAAAPIQwFBQwMBQwMBQwMBQUMIgQEBAQEBAQEBAQEBAQEBAQEEgQEBAQEBAQEBAQEBBIE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE" +
                    "BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBBIEBAQEBAQEBAQEBAQSBAQEBAQEBAQE" +
                    "BAQEBAQEBAQ="
            ),
            template("tower_base", 7, 7, 7,
                    "/////////////////////////////////////////zD///////8B////////////////////////////////////////////" +
                    "//////////8w////////Af//////////////////////////////////////////////////////MP///////wH/////////" +
                    "////AAAAAAAAAAAAAAAAAAAAAAQEBAAAAAAVBAQAAAAABAQEAAAAAAAAAAAAAAAAAAAAAAQEBAQEBAQEBAEBAQQEBAEEFQQB" +
                    "BAQBBAQEAQQEAQQEBAEEBAQBAQEEBAQEBAQEBAQEBAQLBAQEBAQBEwEEBAQBBAQEAQQIFgQEFRYPBAEEBAQBBAQEARMBBAQE" +
                    "BAQMBAQEBAQEBAQEBAQEAQEBBAQEAQQEBAEEBAEEBAQBBAQBBBUEAQQEBAEBAQQEBAQEBAQEBA=="
            ),
            template("tower_floor", 7, 4, 7,
                    "BAcLCwspBCAxAAAAMw4IAAAAAAAPCAAAAAAADwgAAAAAAA8KMgAAADQiBCEMDAwRBAQEBAQEBAQEBAEBAQQEBAEEFQQBBAQB" +
                    "BAQEAQQEAQQEBAEEBAQBAQEEBAQEBAQEBAQEBAQLBAQEBAQBAQEEBAQBBAQEAQQIAQQEFQEPBAEEBAQBBAQEAQEBBAQEBAQM" +
                    "BAQEBAQEBAQEBAQEAQEBBAQEAQQEBAEEBAEEBAQBBAQBBBUEAQQEBAEBAQQEBAQEBAQEBA=="
            ),
            template("tower_piece", 7, 4, 7,
                    "BAQEBAQEBAQEAAAABAQEAAQEBAAEBAAVBAQABAQABAQEAAQEBAAAAAQEBAQEBAQEBAQEBAQEBAQEBAEBAQQEBAEEFQQBBAQB" +
                    "BAQEAQQEAQQEBAEEBAQBAQEEBAQEBAQEBAQEBAQLBAQEBAQBEwEEBAQBBAQEAQQIFgQEFRYPBAEEBAQBBAQEARMBBAQEBAQM" +
                    "BAQEBAQEBAQEBAQEAQEBBAQEAQQEBAEEBAEEBAQBBAQBBBUEAQQEBAEBAQQEBAQEBAQEBA=="
            ),
            template("tower_top", 9, 5, 9,
                    "BAQ2BAQENgQEBAcLDQsNCykENQgAAAAAAA84BAkAFRUAABAEBAgABAQEAA8EBAkABAQEABAENQgAAAAAAA84BCEMBQwFDCIE" +
                    "BAQ3BAQENwQEBAQEBAQEBAQEBBIEBAQEBBIEBAQBAgICAQQEBAQCBAQEBAQEBAQCBAQEBAQEBAQCBAQEAgQEBAQBAgICAQQE" +
                    "BBIEBAQEBBIEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQBAgMCAQQEBAQCBAQEBAQEBAQDBAQEBAQEBAQCBAQEAgQE" +
                    "BAQBAgMCAQQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQBAgMCAQQEBAQCBAQEAgQEBAQDBAYEAgQE" +
                    "BAQCBAQEAgQEBAQBAgMCAQQEBAQEBAQEBAQEBAQEBAQEBAQEBwsNDQsNDQsOCAAAAAAAAAAPCQAAAAAAAAAQCQAAAAAAAAAQ" +
                    "CAAAAAAAAAAPCQAAAAAAAAAQCQAAAAAAAAAQCAAAAAAAAAAPCgwFBQwFBQwR",
                    new Marker(4, 3, 4, "Sentry")
            ));

    public static Template byName(String name) {
        for (Template template : TEMPLATES) {
            if (template.name().equals(name)) return template;
        }
        throw new IllegalArgumentException("unknown end city template " + name);
    }
}
